"""add room_memory table

Revision ID: 1b2b5f95d667
Revises: a168601292ab
Create Date: 2026-02-08 00:03:10.505789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b2b5f95d667'
down_revision: Union[str, Sequence[str], None] = 'a168601292ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_memory',
    sa.Column('room_id', sa.INTEGER(), nullable=False),
    sa.Column('summary', sa.TEXT(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_memory')
    # ### end Alembic commands ###
