"""remove reply_to_message_id from messages

Revision ID: a168601292ab
Revises: 808faff99f20
Create Date: 2026-02-04 18:49:31.981550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a168601292ab'
down_revision: Union[str, Sequence[str], None] = '808faff99f20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('messages_reply_to_message_id_fkey'), 'messages', type_='foreignkey')
    op.drop_column('messages', 'reply_to_message_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reply_to_message_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('messages_reply_to_message_id_fkey'), 'messages', 'messages', ['reply_to_message_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
